Clean Architecture, Repository-service pattern, working on controller
Have problem with mapping data to circuit. Error type:
500
Undocumented

Error: Internal Server Error
AutoMapper.AutoMapperMappingException: Error mapping types.
Mapping types:
List`1 -> List`1

System.Collections.Generic.List`1[[Diplomska.Domain.Models.Circuit, Diplomska.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.List`1[[Diplomska.Service.Dtos.CircuitGetDto, Diplomska.Service, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]

 ---> AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.