Changes to DriverStanding
Error in SeedData:
Error: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Diplomska.Domain.Models.Constructor' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'MRData.StandingsTable.StandingsLists[0].DriverStandings[0].Constructors', line 1, position 587.
Error: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Diplomska.Domain.Models.Constructor' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'MRData.StandingsTable.StandingsLists[0].DriverStandings[0].Constructors', line 1, position 587.

Co-Authored-By: marsenovska <25085110+marsenovska@users.noreply.github.com>